---
- name: Check if we have any hosts in the inventory
  hosts: localhost
  tasks:
    - fail:
        msg: "[ERROR] Empty inventory. No host available."
      when: groups.all|length == 0
      
- name: Prepare the image with the STFC security baseline
  hosts: all
  pre_tasks:
    - name: User warning
      ansible.builtin.debug:
        msg: "[Warning] Do not run on non-cloud machine"

  roles:
    - role: vm_baseline
    - role: container_registry
    - role: nubes_bootcontext
    - role: image_fixes
    - role: tidy_image
    