
- name: Install cron on Ubuntu
  ansible.builtin.apt:
    name: "cron"
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

- name: Install cron on RL
  ansible.builtin.yum:
    name: "cronie"
    state: present
  become: true
  when: ansible_os_family == "RedHat" 
