- name: Copy Pakiti RPM
  copy:
    src: "files/pakiti-client-2.1.4-3.RAL.noarch.rpm"
    dest: "/tmp/pakiti-client-2.1.4-3.RAL.noarch.rpm"

- name: Install Pakiti on Ubuntu using Alien
  block:
    - name: Enable Universe for Alien
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} main"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} universe"

    - name: Install Alien for Pakiti
      apt:
        name: alien
        state: present
        update_cache: yes

    - name: Install Pakiti using Alien
      command:
        cmd: "alien --install /tmp/pakiti-client-2.1.4-3.RAL.noarch.rpm"

    - name: Remove Alien
      apt:
        name: alien
        state: absent

    - name: Remove universe repository
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} universe"
        state: absent

    - name: Update apt-cache
      apt:
        update_cache: yes
  when: ansible_os_family == "Debian" and 'pakiti-client' not in ansible_facts.packages

- name: Install Pakiti on RL
  yum:
    name: "/tmp/pakiti-client-2.1.4-3.RAL.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: ansible_os_family == "RedHat" 

- name: Ensure pakiti config directory exists
  file:
    path: "/etc/pakiti2"
    state: directory
    owner: root
    group: root
    mode: 0644


- name: Copy pakiti config file
  copy:
    src: "etc/pakiti2/pakiti2-client.conf"
    dest: "/etc/pakiti2/pakiti2-client.conf"
    owner: root
    group: root
    mode: 0644
