- name: Clear EL audits
  block:
  - name: Clear Audit log
    shell: "/bin/cat /dev/null > /var/log/audit/audit.log"
  when: ansible_os_family == "RedHat"

- name: Clear Audit log
  shell: "/bin/cat /dev/null > /var/log/wtmp"

- name: Clear Ubuntu audits
  block:
  - name: Clear Audit log
    shell: "/bin/cat /dev/null > /var/log/auth.log"
  when: ansible_os_family == "Debian"
