- name: Cleanout *.rpm
  file:
    path: "*.rpm"
    state: absent

- name: Cleanout *.deb
  file:
    path: "*.deb"
    state: absent

- name: clean yum/dnf
  command: yum clean all
  when: ansible_os_family == "RedHat"

- name: clean apt cache
  ansible.builtin.apt:
    clean: yes
  when: ansible_os_family == "Debian"
