- name: Remove duplicate /etc/logrotate.d/btmp
  file:
    path: "/etc/logrotate.d/btmp"
    state: absent
  when: ansible_distribution == "Rocky" 
  become: true

- name: Remove duplicate /etc/logrotate.d/wtmp
  file:
    path: "/etc/logrotate.d/wtmp"
    state: absent
  when: ansible_distribution == "Rocky" 
  become: true


- name: Clear Audit log
  shell: "logrotate -f /etc/logrotate.conf"
  become: true

- name: Cleanout /var/log/*.gz
  file:
    path: "/var/log/*.gz"
    state: absent
  become: true
