- name: Cleanout Host SSH Keys
  file:
    path: "/home/*/.bash_history"
    state: absent
  become: true

- name: Cleanout Host SSH Keys
  file:
    path: "/root/.bash_history"
    state: absent
  become: true
