# - name: set locale to set
#   set_fact:
#     config_system_locale: "en_GB.UTF-8"
#     config_system_language: "en_GB.UTF-8"

- name: set locale to set
  set_fact:
    config_system_locale: "en_US.UTF-8"
    config_system_language: "en_US.UTF-8"

- name: check if locale exists
  shell: "locale -a | grep -i {{ config_system_locale | regex_replace('-', '') | quote }}"
  register: found_locale
  changed_when: no
  failed_when: no
  become: true

- name: create locale
  command: "localedef -i {{ config_system_locale | regex_replace('(.*)\\..*', '\\1') | quote }} -f {{ config_system_locale | regex_replace('.*\\.(.*)', '\\1') | quote }} {{ config_system_locale | quote }}"
  when: not ansible_check_mode and found_locale.rc != 0
  become: true

- name: check if language exists
  shell: "locale -a | grep -i {{ config_system_language | regex_replace('-', '') | quote }}"
  register: found_language
  changed_when: no
  failed_when: no
  become: true

- name: create language
  command: "localedef -i {{ config_system_language | regex_replace('(.*)\\..*', '\\1') | quote }} -f {{ config_system_language | regex_replace('.*\\.(.*)', '\\1') | quote }} {{ config_system_language | quote }}"
  when: not ansible_check_mode and found_language.rc != 0
  become: true

- name: Get current locale and language configuration
  command: localectl status
  register: locale_status
  changed_when: false
  become: true

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  become: true

- name: Set locale keymap
  command: localectl set-keymap gb
  when: ansible_distribution == "Rocky"
  become: true

# - name: Set locale keymap
#   command: loadkeys uk
#   when: ansible_distribution == "Ubuntu"


# - name: Set locale x11 keymap
#   command: localeclt set-x11-keymap gb
#   when: ansible_distribution == "Rocky"
