- name: Set wazuh package name variable
  set_fact:
    wazuh_package_name: "wazuh-agent"

- name: Stop wazuh-agent service
  become: true
  ansible.builtin.command:
    cmd: "systemctl stop wazuh-agent.service"
  when: wazuh_package_name in ansible_facts.packages
  ignore_errors: True
  become: true

- name: Clean Wazuh agent history
  file:
    path: "/var/ossec/etc/client.keys"
    state: absent
  become: true
